[project]
name = "jcx"
version = "0.4.0"
description = ""
readme = "README.md"
authors = [
    { name = "dayn9t", email = "dayn9t@gmail.com" }
]
requires-python = "~=3.12"

dependencies = [
    "rustshed",
    "pydantic",
    "typer",
    "loguru",
    "arrow",
    "paho-mqtt",
    "parse",
    "redis",
    "requests",
    "sh",
    "interval",
    "numpy",
    "types-paho-mqtt",
    "poetry-core (>=2.1.3,<3.0.0)",
]


[tool.poetry.group.test.dependencies]
pytest = "*"


[tool.poetry.group.dev.dependencies]
black = "*"
mypy = "*"
pre-commit = "*"
nuitka = "*"


[tool.ruff]
ignore = ["F403", "F405"]

[tool.ruff.lint]
#select = ["E4", "E7", "E9", "F"]
select = ["ALL"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
