[project]
name = "jcx"
version = "0.4.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dayn9t", email = "dayn9t@gmail.com" }
]
requires-python = "~=3.12"
dependencies = [
    "rustshed",
    "pydantic",
    "typer",
    "loguru",
    "arrow",
    "paho-mqtt",
    "parse",
    "redis",
    "requests",
    "sh",
    "interval",
    "numpy",
    "types-paho-mqtt",
]

[project.scripts]
jcx = "jcx:main"

[tool.ruff]
ignore = ["F403", "F405"]

[tool.ruff.lint]
#select = ["E4", "E7", "E9", "F"]
select = ["ALL"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
