[project]
name = "jcx"
version = "0.4.9"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dayn9t", email = "dayn9t@gmail.com" }
]
requires-python = "~=3.12.0"
dependencies = [
    "rustshed",
    "pydantic",
    "pydantic-extra-types",
    "typer",
    "arrow",
    "loguru",

    "paho-mqtt",
    "types-paho-mqtt",
    "parse",
    "redis",
    "requests",
    "sh",
    "interval",
    "numpy",
]

[project.scripts]
#cx_rename = "src/jcx/bin/cx_rename.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest",
]

