[tool.poetry]
name = "jcx"
version = "0.1.5"
description = ""
authors = ["dayn9t <dayn9t@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "*"

arrow = "*"
loguru = "*"
paho-mqtt = "*"
parse = "*"
redis = "*"
requests = "*"
sh = "*"
interval = "*"

numpy = "*"

rustshed = "*"
pytest = "*"
mypy = "*"
pre-commit = "*"
types-paho-mqtt = "*"




[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
