[project]
name = "jcx"
version = "0.4.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dayn9t", email = "dayn9t@gmail.com" }
]
requires-python = "~=3.12"
dependencies = [
    "rustshed",
    "pydantic",
    "typer",
    "loguru",
    "arrow",
    "paho-mqtt",
    "parse",
    "redis",
    "requests",
    "sh",
    "interval",
    "numpy",
    "types-paho-mqtt",
]

[project.scripts]
cx_rename = "jcx/bin/cx_rename.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
