target-version = "py312"
line-length = 88

[lint]
select = ["ALL"]
ignore = ["F403", "F405", "D203", "D213", "COM812"]

[lint.per-file-ignores]
"tests/*" = ["S101"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
